### PR TITLE
Add GitHub Enterprise support

### PR DESCRIPTION
**Pull request by dmaticzka**
References Actions default environment variable GITHUB_SERVER_URL to allow use with servers other than github.com.

### CODE REVIEW

**Review by gautamkrishnar — CHANGES_REQUESTED** [review]
@dmaticzka can you please revert the changes you made to dist/index.js

**Comment by dmaticzka** [comment]
Sure, here we go.

**Comment by gautamkrishnar** [comment]
@dmaticzka thanks a lot for contributing 🎉

**Review by gautamkrishnar — APPROVED** [review]

**Comment by gautamkrishnar** [comment]
@all-contributors please add @dmaticzka for code

**Pull request merged**
